FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl libssl3 libmariadb3 libpq5 libsqlite3-0 unixodbc libjson-c5 libapr1 \
    libaprutil1 wget gnupg && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY ./src/build/cm /usr/bin/cm
RUN chmod +x /usr/bin/cm
EXPOSE 2310 2443
CMD ["bash"]