#!/bin/bash

# test - helloworld
URL="http://localhost:2310/api/helloworld"
RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
if [ "$RESPONSE" -ne 200 ]; then
  exit 1
fi

echo "Done."
exit 0
