name: test
on:
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
  pull_request:
    paths:
      - 'src/**'
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.dev -t "test-image" .
      - name: Run Tests in Docker Container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/service \
          -w /service \
          --name "test-container" \
          "test-image" \
          bash -c "
            cd /service/src &&
            make test &&
            make run-test
          "
